#!/usr/bin/env sh

set -xe

# MARLIN_VERSION: https://github.com/MarlinFirmware/Marlin
# PLATFORMIO_CORE_VERSION: https://github.com/platformio/platformio-core-installer

docker build \
  --build-arg="MARLIN_VERSION=2.1.2.2" \
  --build-arg="MARLIN_SHA256=67351439369f9a267231e7280314a2a13bb1919a736a02f9410b26d8f78f221e" \
  --build-arg="PLATFORMIO_CORE_VERSION=1.2.2" \
  --build-arg="PLATFORMIO_CORE_SHA256=068d5dca983b22ed36a00dea7d42e58b646f0ac495885892f5746357f39a0470" \
  --tag=marlin \
  "$PWD"

# ref: https://marlinfw.org/docs/basics/install_platformio_vscode.html#6.-find-and-set-build-environment
ENVIRONMENT=STM32G0B1RE_btt

docker run \
  --rm \
  --interactive \
  --tty \
  --volume="marlin-platformio:/home/app/.platformio" \
  --volume="$PWD/pio:/home/app/marlin/.pio" \
  $(ls -A1 config | xargs -I {} echo "--volume=$PWD/config/{}:/home/app/marlin/Marlin/{}") \
  marlin \
  platformio run -e "$ENVIRONMENT"
